name: build-and-deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  BOT_NAME: discord-bot
  DOCKER_TAG: ver-${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: docker build . --file Dockerfile --tag discord-bot:build

      - name: docker tag
        run: docker tag ${{ env.BOT_NAME }}:${{ env.DOCKER_TAG }} ${{secrets.DOCKER_USER}}/discord-bot:test

      - name: docker push
        run: docker push ${{secrets.DOCKER_USER}}/${{ env.BOT_NAME }}:${{ env.DOCKER_TAG }}
